openapi: 3.0.0
info:
  title: RAG Agent API
  version: 1.0.0
paths:
  /chat:
    post:
      summary: Send a query to the RAG Agent
      operationId: queryAgent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Validation error
        '500':
          description: Server error

components:
  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
        thread_id:
          type: string
    QueryResponse:
      type: object
      required:
        - response
        - status
      properties:
        response:
          type: string
        thread_id:
          type: string
        status:
          type: string
          enum: [success, error]
